### ISSUE TITLE
Checklist para 20/04

### ISSUE THREAD

**Issue by CrisMendonca** [CrisMendonca/Projeto_Integrador#12]
S3

- [x] Criar 2 buckets no s3

digitalhouse_{nome_do_seu_grupo}_homolog
digitalhouse_{nome_do_seu_grupo}_producao

- [ ] Criar ACL’s específicos para cada bucket

user_homolog => digitalhouse_{nome_do_seu_grupo}_homolog
user_producao => digitalhouse_{nome_do_seu_grupo}_producao

- [ ] Obter os tokens de acesso (Aula 2 de AWS - S3)

Deploys simples
Pipeline simples para deploys em Homolog ou Producao  com os apps: Node App01 ou Node App02
